version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: increase
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      composer:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - ci
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      actions:
        patterns:
          - "*"
